apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: op4-kube-backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: web
      port: 8081
      targetPort: web
